name: CI
on: push
env:
  DEPLOYER_PRIVATEKEY: 0x0000000000000000000000000000000000000000000000000000000000000000
  SECRETS_FILE: ${{secrets.SECRETS_FILE}}

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: echo "$SECRETS_FILE" | base64 -d > .env

      - name: Use Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Components
        run: yarn install

      - name: Run Trinity tests
        run: yarn test test/trinity/*.js
        #run: yarn test
